# Generated by Django 6.0.6 on 2026-06-16 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('movement', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('QUARTZ', 'Quartz'), ('MANUAL', 'Manual Winding')], max_length=20)),
                ('case_size', models.IntegerField(help_text='Size in mm')),
                ('water_resistance', models.CharField(default='50m', max_length=50)),
                ('strap_material', models.CharField(max_length=100)),
                ('primary_image', models.ImageField(upload_to='watches/')),
                ('secondary_image', models.ImageField(help_text='Shown on hover', upload_to='watches/')),
                ('stock', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='store.brand')),
            ],
        ),
    ]
